const DEFAULT_STATUS = 'DEFAULT_STATUS';
const LOADING_STATUS = 'LOADING_STATUS';
const SUCCESS_STATUS = 'SUCCESS_STATUS';
const ERROR_STATUS = 'ERROR_STATUS';

export {
  DEFAULT_STATUS,
  LOADING_STATUS,
  SUCCESS_STATUS,
  ERROR_STATUS,
};
