const STATE_DEFAULT = 'STATE_DEFAULT';
const STATE_LOADING = 'STATE_LOADING';
const STATE_SUCCESS = 'STATE_SUCCESS';
const STATE_ERROR = 'STATE_ERROR';

export {
  STATE_DEFAULT,
  STATE_LOADING,
  STATE_SUCCESS,
  STATE_ERROR,
};
